
- name: "Application setup for {{ component }}"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "app-setup.yaml"

- name: "Node JS setup for {{ component }}"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "nodejs-setup.yaml"

- name: "Systemd Setup for {{ component }}"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "systemd-setup.yaml"

- name: copy mongo repo
  ansible.builtin.copy:
    src: files/mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: "Install MongoDB client for {{ component }}"
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
  
- name: "check products loaded"
  ansible.builtin.command: mongo --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: "Load products data"
  ansible.builtin.command: mongo --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: "Start {{ component }} service"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes